export const APP_ROUTES = {
    HOME: '/',
    CARTA_RESTAURANTE: '/carta-restaurante',
    RESERVA_RESTAURANTE: '/reservar',
    CARTA_LLEVAR: '/carta-llevar',
    CARTA_DESAYUNOS_ALMUERZOS: '/carta-desayunos-almuerzos',
    CARTA_PAELLAS_DOMICILIO: '/carta-paellas-domicilio-elche',
    MAIN_RESTAURANT: "https://maps.app.goo.gl/YNQkjVPUNcEciiMw9",
    MAIN_RESTAURANT_PHONE: "+34 671 40 15 36",
    LOCAL1: "https://maps.app.goo.gl/usUG4Zkwtos5XoUC6?g_st=iw",
    LOCAL1_PHONE: "+34 656 55 70 49",
    LOCAL2: "https://maps.app.goo.gl/x7q2nqYraxRJAna46",
    LOCAL2_PHONE: "+34 645 53 94 69",
    FACEBOOK: "https://www.facebook.com/casasimoncomidas/?locale=es_LA",
    INSTAGRAM: "https://www.instagram.com/casasimoncomidas/",
    AVISO_LEGAL: '/aviso-legal',
    PRIVACIDAD: '/privacidad',
    BLOG: '/blog',
    BLOG_POST_PAELLA: '/blog/paellas-lena-elche',
    BLOG_POST_CARNES: '/blog/carnes-brasa-elche-chuletón',
    BLOG_POST_LOCALES: '/blog/comida-para-llevar-elche-altabix',
    BLOG_POST_DOMICILIO: '/blog/paellas-para-llevar-elche-domicilio',
    BLOG_POST_ALMUERZOS: '/blog/almuerzos-populares-elche-bocadillos',
    BLOG_POST_POSTRES: '/blog/postres-caseros-tarta-elche',
    ALERGENOS_PARALLEVAR: '/alergenos-local', 
    ALERGENOS_RESTAURANTE: '/alergenos-restaurante',



};